---

run:
  tests: false

linters:
  enable:
  - asciicheck
  - bodyclose
  - cyclop
  - depguard
  - dogsled
  - dupl
  - durationcheck
  - errname
  - errorlint
  - exhaustive
  - exportloopref
  - forbidigo
  - forcetypeassert
  - funlen
  - gochecknoglobals
  - gochecknoinits
  - gocognit
  - goconst
  - gocritic
  - gocyclo
  - godox
  - gofmt
  - gofumpt
  - goheader
  - goimports
  - gomoddirectives
  - gomodguard
  - goprintffuncname
  - importas
  - makezero
  - misspell
  - nakedret
  - nestif
  - nilerr
  - nlreturn
  - nolintlint
  - prealloc
  - predeclared
  - promlinter
  - revive
  - rowserrcheck
  - sqlclosecheck
  - stylecheck
  - tagliatelle
  - testpackage
  - thelper
  - tparallel
  - unconvert
  - unparam
  - wastedassign
  - whitespace
  disable:
  - paralleltest # need to wait for tests rework

    # these ones should be enabled later with dedicated PR to fix them
  - gosec
  - gomnd
  - noctx
  - goerr113
